name: Django CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  ci:
    runs-on: ubuntu-latest

    environment: test

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          python manage.py migrate

      - name: Run tests
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          python manage.py test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/django-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/django-app:${{ github.sha }}

#-------------------------------------------------------------------------------------#
                          #CD
#-------------------------------------------------------------------------------------#
  cd:
    needs: ci

    runs-on: ubuntu-latest

    environment: production

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            # Login to Docker Hub
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
            docker login \
              --username "${{ secrets.DOCKERHUB_USERNAME }}" \
              --password-stdin

            # Pull image created by CI
            docker pull \
              ${{ secrets.DOCKERHUB_USERNAME }}/django-app:${{ github.sha }}

            # Stop old container
            docker stop django-app || true

            # Remove old container
            docker rm django-app || true

            # Start new container
            docker run -d \
              --name django-app \
              --restart unless-stopped \
              -p 8000:8000 \
              -e DB_NAME="${{ secrets.DB_NAME }}" \
              -e DB_USER="${{ secrets.DB_USER }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e DB_HOST="${{ secrets.DB_HOST }}" \
              -e DB_PORT="${{ secrets.DB_PORT }}" \
              ${{ secrets.DOCKERHUB_USERNAME }}/django-app:${{ github.sha }}

            # Run Django migrations on RDS
            docker exec django-app \
              python manage.py migrate